---
version: "2.4"

volumes:
  minio-data:

services:
  postgres:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
