---
version: "2.4"

volumes:
  minio-data:

services:
  postgres:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  minio:
    image: docker.io/minio/minio:RELEASE.2021-08-25T00-41-18Z.hotfix.fa57120f2
    restart: always
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=miniopass
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
